openapi: 3.0.0
info:
  title: Study Tracker API - Users
  version: 1.0.0
paths:
  /api/users:
    get:
      summary: Returns a list of users
      tags:
        - Users
      parameters:
        - in: query
          name: name
          schema:
            type: string
          description: Filter by name
        - in: query
          name: email
          schema:
            type: string
          description: Filter by email
        - in: query
          name: page
          schema:
            type: integer
        - in: query
          name: limit
          schema:
            type: integer
      responses:
        '200':
          description: List of users with pagination
        '500':
          description: Unexpected server error
    post:
      summary: Create a new user
      tags:
        - Users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
              required:
                - name
                - email
      responses:
        '201':
          description: User created successfully
        '400':
          description: Invalid input
        '500':
          description: Unexpected server error

  /api/users/{id}:
    parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
        description: The user ID
    get:
      summary: Get a user by ID
      tags:
        - Users
      responses:
        '200':
          description: User object
        '404':
          description: User not found
        '500':
          description: Unexpected server error
    put:
      summary: Update a user by ID
      tags:
        - Users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
      responses:
        '200':
          description: User updated successfully
        '400':
          description: Invalid input
        '404':
          description: User not found
        '500':
          description: Unexpected server error
    delete:
      summary: Delete a user by ID
      tags:
        - Users
      responses:
        '204':
          description: User deleted successfully
        '404':
          description: User not found
        '500':
          description: Unexpected server error